# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timing_Client.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TimingClient(object):
    def setupUi(self, TimingClient):
        TimingClient.setObjectName(_fromUtf8("TimingClient"))
        TimingClient.resize(1312, 863)
        self.centralwidget = QtGui.QWidget(TimingClient)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.CurrentImportTab = QtGui.QTabWidget(self.centralwidget)
        self.CurrentImportTab.setGeometry(QtCore.QRect(10, 30, 1291, 801))
        self.CurrentImportTab.setObjectName(_fromUtf8("CurrentImportTab"))
        self.CurrentTiming = QtGui.QWidget()
        self.CurrentTiming.setObjectName(_fromUtf8("CurrentTiming"))
        self.CurrentSave = QtGui.QPushButton(self.CurrentTiming)
        self.CurrentSave.setGeometry(QtCore.QRect(1190, 10, 71, 21))
        self.CurrentSave.setObjectName(_fromUtf8("CurrentSave"))
        self.CurrentViewType = QtGui.QTabWidget(self.CurrentTiming)
        self.CurrentViewType.setGeometry(QtCore.QRect(10, 30, 1261, 741))
        self.CurrentViewType.setObjectName(_fromUtf8("CurrentViewType"))
        self.CurrentAllSeqTab = QtGui.QWidget()
        self.CurrentAllSeqTab.setObjectName(_fromUtf8("CurrentAllSeqTab"))
        self.CurrentAllSeqTable = QtGui.QTableWidget(self.CurrentAllSeqTab)
        self.CurrentAllSeqTable.setGeometry(QtCore.QRect(130, 11, 901, 691))
        self.CurrentAllSeqTable.setObjectName(_fromUtf8("CurrentAllSeqTable"))
        self.CurrentAllSeqTable.setColumnCount(0)
        self.CurrentAllSeqTable.setRowCount(0)
        self.CurrentViewType.addTab(self.CurrentAllSeqTab, _fromUtf8(""))
        self.CurrentGraphTab = QtGui.QWidget()
        self.CurrentGraphTab.setObjectName(_fromUtf8("CurrentGraphTab"))
        self.CurrentGraphPlot = MatplotlibWidget(self.CurrentGraphTab)
        self.CurrentGraphPlot.setGeometry(QtCore.QRect(380, 30, 721, 651))
        self.CurrentGraphPlot.setObjectName(_fromUtf8("CurrentGraphPlot"))
        self.CurrentGraphDevList = QtGui.QListWidget(self.CurrentGraphTab)
        self.CurrentGraphDevList.setGeometry(QtCore.QRect(170, 120, 141, 321))
        self.CurrentGraphDevList.setObjectName(_fromUtf8("CurrentGraphDevList"))
        self.CurrentGraphLabelSeq = QtGui.QLabel(self.CurrentGraphTab)
        self.CurrentGraphLabelSeq.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.CurrentGraphLabelSeq.setObjectName(_fromUtf8("CurrentGraphLabelSeq"))
        self.CurrentGraphLabelDevice = QtGui.QLabel(self.CurrentGraphTab)
        self.CurrentGraphLabelDevice.setGeometry(QtCore.QRect(200, 90, 53, 16))
        self.CurrentGraphLabelDevice.setObjectName(_fromUtf8("CurrentGraphLabelDevice"))
        self.CurrentGraphSeqList = QtGui.QListWidget(self.CurrentGraphTab)
        self.CurrentGraphSeqList.setGeometry(QtCore.QRect(10, 120, 131, 321))
        self.CurrentGraphSeqList.setObjectName(_fromUtf8("CurrentGraphSeqList"))
        self.CurrentViewType.addTab(self.CurrentGraphTab, _fromUtf8(""))
        self.CurrentValuesTab = QtGui.QWidget()
        self.CurrentValuesTab.setObjectName(_fromUtf8("CurrentValuesTab"))
        self.CurrentValuesListTable = QtGui.QTableWidget(self.CurrentValuesTab)
        self.CurrentValuesListTable.setGeometry(QtCore.QRect(300, 10, 941, 691))
        self.CurrentValuesListTable.setObjectName(_fromUtf8("CurrentValuesListTable"))
        self.CurrentValuesListTable.setColumnCount(0)
        self.CurrentValuesListTable.setRowCount(0)
        self.CurrentValuesDevList = QtGui.QListWidget(self.CurrentValuesTab)
        self.CurrentValuesDevList.setGeometry(QtCore.QRect(150, 120, 121, 381))
        self.CurrentValuesDevList.setObjectName(_fromUtf8("CurrentValuesDevList"))
        self.CurrentValuesLabelSeq = QtGui.QLabel(self.CurrentValuesTab)
        self.CurrentValuesLabelSeq.setGeometry(QtCore.QRect(40, 90, 61, 16))
        self.CurrentValuesLabelSeq.setObjectName(_fromUtf8("CurrentValuesLabelSeq"))
        self.CurrentValuesLabelDevice = QtGui.QLabel(self.CurrentValuesTab)
        self.CurrentValuesLabelDevice.setGeometry(QtCore.QRect(190, 90, 53, 16))
        self.CurrentValuesLabelDevice.setObjectName(_fromUtf8("CurrentValuesLabelDevice"))
        self.CurrentValuesSeqList = QtGui.QListWidget(self.CurrentValuesTab)
        self.CurrentValuesSeqList.setGeometry(QtCore.QRect(10, 120, 121, 381))
        self.CurrentValuesSeqList.setObjectName(_fromUtf8("CurrentValuesSeqList"))
        self.CurrentViewType.addTab(self.CurrentValuesTab, _fromUtf8(""))
        self.AutoUpdate = QtGui.QCheckBox(self.CurrentTiming)
        self.AutoUpdate.setGeometry(QtCore.QRect(920, 10, 101, 17))
        self.AutoUpdate.setObjectName(_fromUtf8("AutoUpdate"))
        self.Update = QtGui.QPushButton(self.CurrentTiming)
        self.Update.setGeometry(QtCore.QRect(1030, 10, 75, 23))
        self.Update.setObjectName(_fromUtf8("Update"))
        self.CurrentImportTab.addTab(self.CurrentTiming, _fromUtf8(""))
        self.ImportedTiming = QtGui.QWidget()
        self.ImportedTiming.setObjectName(_fromUtf8("ImportedTiming"))
        self.Import = QtGui.QPushButton(self.ImportedTiming)
        self.Import.setGeometry(QtCore.QRect(1040, 10, 111, 20))
        self.Import.setObjectName(_fromUtf8("Import"))
        self.ImportSave = QtGui.QPushButton(self.ImportedTiming)
        self.ImportSave.setGeometry(QtCore.QRect(1170, 10, 81, 20))
        self.ImportSave.setObjectName(_fromUtf8("ImportSave"))
        self.ImportViewType = QtGui.QTabWidget(self.ImportedTiming)
        self.ImportViewType.setGeometry(QtCore.QRect(10, 20, 1271, 751))
        self.ImportViewType.setObjectName(_fromUtf8("ImportViewType"))
        self.ImportAllSeqTab = QtGui.QWidget()
        self.ImportAllSeqTab.setObjectName(_fromUtf8("ImportAllSeqTab"))
        self.ImportAllSeqTable = QtGui.QTableWidget(self.ImportAllSeqTab)
        self.ImportAllSeqTable.setGeometry(QtCore.QRect(130, 11, 901, 691))
        self.ImportAllSeqTable.setObjectName(_fromUtf8("ImportAllSeqTable"))
        self.ImportAllSeqTable.setColumnCount(0)
        self.ImportAllSeqTable.setRowCount(0)
        self.ImportViewType.addTab(self.ImportAllSeqTab, _fromUtf8(""))
        self.ImportGraphTab = QtGui.QWidget()
        self.ImportGraphTab.setObjectName(_fromUtf8("ImportGraphTab"))
        self.ImportGraphDevList = QtGui.QListWidget(self.ImportGraphTab)
        self.ImportGraphDevList.setGeometry(QtCore.QRect(150, 120, 151, 321))
        self.ImportGraphDevList.setObjectName(_fromUtf8("ImportGraphDevList"))
        self.ImportGraphLabelSeq = QtGui.QLabel(self.ImportGraphTab)
        self.ImportGraphLabelSeq.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.ImportGraphLabelSeq.setObjectName(_fromUtf8("ImportGraphLabelSeq"))
        self.ImportGraphLabelDevice = QtGui.QLabel(self.ImportGraphTab)
        self.ImportGraphLabelDevice.setGeometry(QtCore.QRect(210, 90, 53, 16))
        self.ImportGraphLabelDevice.setObjectName(_fromUtf8("ImportGraphLabelDevice"))
        self.ImportGraphSeqList = QtGui.QListWidget(self.ImportGraphTab)
        self.ImportGraphSeqList.setGeometry(QtCore.QRect(10, 120, 121, 321))
        self.ImportGraphSeqList.setObjectName(_fromUtf8("ImportGraphSeqList"))
        self.graphicsView = PlotWidget(self.ImportGraphTab)
        self.graphicsView.setGeometry(QtCore.QRect(390, 60, 701, 541))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.ImportViewType.addTab(self.ImportGraphTab, _fromUtf8(""))
        self.ImportValuesTab = QtGui.QWidget()
        self.ImportValuesTab.setObjectName(_fromUtf8("ImportValuesTab"))
        self.ImportValuesListTable = QtGui.QTableWidget(self.ImportValuesTab)
        self.ImportValuesListTable.setGeometry(QtCore.QRect(340, 10, 911, 691))
        self.ImportValuesListTable.setObjectName(_fromUtf8("ImportValuesListTable"))
        self.ImportValuesListTable.setColumnCount(0)
        self.ImportValuesListTable.setRowCount(0)
        self.ImportValuesDevList = QtGui.QListWidget(self.ImportValuesTab)
        self.ImportValuesDevList.setGeometry(QtCore.QRect(180, 120, 121, 381))
        self.ImportValuesDevList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.ImportValuesDevList.setObjectName(_fromUtf8("ImportValuesDevList"))
        self.ImportValuesLabelSeq = QtGui.QLabel(self.ImportValuesTab)
        self.ImportValuesLabelSeq.setGeometry(QtCore.QRect(40, 90, 61, 16))
        self.ImportValuesLabelSeq.setObjectName(_fromUtf8("ImportValuesLabelSeq"))
        self.ImportValuesLabelDevice = QtGui.QLabel(self.ImportValuesTab)
        self.ImportValuesLabelDevice.setGeometry(QtCore.QRect(220, 90, 53, 16))
        self.ImportValuesLabelDevice.setObjectName(_fromUtf8("ImportValuesLabelDevice"))
        self.ImportValuesSeqList = QtGui.QListWidget(self.ImportValuesTab)
        self.ImportValuesSeqList.setGeometry(QtCore.QRect(10, 120, 121, 381))
        self.ImportValuesSeqList.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.ImportValuesSeqList.setObjectName(_fromUtf8("ImportValuesSeqList"))
        self.ImportViewType.addTab(self.ImportValuesTab, _fromUtf8(""))
        self.CurrentImportTab.addTab(self.ImportedTiming, _fromUtf8(""))
        self.Close = QtGui.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(1240, 10, 51, 21))
        self.Close.setObjectName(_fromUtf8("Close"))
        TimingClient.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TimingClient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        TimingClient.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TimingClient)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TimingClient.setStatusBar(self.statusbar)

        self.retranslateUi(TimingClient)
        self.CurrentImportTab.setCurrentIndex(0)
        self.CurrentViewType.setCurrentIndex(2)
        self.ImportViewType.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TimingClient)

    def retranslateUi(self, TimingClient):
        TimingClient.setWindowTitle(_translate("TimingClient", "Timing Client", None))
        self.CurrentSave.setText(_translate("TimingClient", "Save to File", None))
        self.CurrentViewType.setTabText(self.CurrentViewType.indexOf(self.CurrentAllSeqTab), _translate("TimingClient", "All Sequences", None))
        self.CurrentGraphLabelSeq.setText(_translate("TimingClient", "Sequence", None))
        self.CurrentGraphLabelDevice.setText(_translate("TimingClient", "Device", None))
        self.CurrentViewType.setTabText(self.CurrentViewType.indexOf(self.CurrentGraphTab), _translate("TimingClient", "Graph", None))
        self.CurrentValuesLabelSeq.setText(_translate("TimingClient", "Sequence", None))
        self.CurrentValuesLabelDevice.setText(_translate("TimingClient", "Device", None))
        self.CurrentViewType.setTabText(self.CurrentViewType.indexOf(self.CurrentValuesTab), _translate("TimingClient", "Values", None))
        self.AutoUpdate.setText(_translate("TimingClient", "Auto Update", None))
        self.Update.setText(_translate("TimingClient", "Update", None))
        self.CurrentImportTab.setTabText(self.CurrentImportTab.indexOf(self.CurrentTiming), _translate("TimingClient", "Current Timing", None))
        self.Import.setText(_translate("TimingClient", "Import Experiment", None))
        self.ImportSave.setText(_translate("TimingClient", "Save to File", None))
        self.ImportViewType.setTabText(self.ImportViewType.indexOf(self.ImportAllSeqTab), _translate("TimingClient", "All Sequences", None))
        self.ImportGraphLabelSeq.setText(_translate("TimingClient", "Sequence", None))
        self.ImportGraphLabelDevice.setText(_translate("TimingClient", "Device", None))
        self.ImportViewType.setTabText(self.ImportViewType.indexOf(self.ImportGraphTab), _translate("TimingClient", "Graph", None))
        self.ImportValuesLabelSeq.setText(_translate("TimingClient", "Sequence", None))
        self.ImportValuesLabelDevice.setText(_translate("TimingClient", "Device", None))
        self.ImportViewType.setTabText(self.ImportViewType.indexOf(self.ImportValuesTab), _translate("TimingClient", "Values", None))
        self.CurrentImportTab.setTabText(self.CurrentImportTab.indexOf(self.ImportedTiming), _translate("TimingClient", "Imported Timing", None))
        self.Close.setText(_translate("TimingClient", "Close", None))

from matplotlibwidget import MatplotlibWidget
from pyqtgraph import PlotWidget
